// Tarjimon qoʻllab-quvvatlaydigan 202 til.
// Interfeys va izohlar — `tillar.h`.

#include "tillar.h"

namespace rubai {
namespace Tillar {

const std::vector<Til>& hammasi() {
    // Tartib macOS'dagi bilan bir xil (nom boʻyicha, registrga sezgir emas).
    static const std::vector<Til> royxat = {
        {"ace_Arab", L"Achin (arab)"},
        {"ace_Latn", L"Achin (lotin)"},
        {"afr_Latn", L"Afrikaans"},
        {"aka_Latn", L"Akan (aka)"},
        {"twi_Latn", L"Akan (twi)"},
        {"als_Latn", L"Alban"},
        {"amh_Ethi", L"Amxar"},
        {"hye_Armn", L"Arman"},
        {"asm_Beng", L"Assam"},
        {"ast_Latn", L"Asturiy"},
        {"awa_Deva", L"Avadxi"},
        {"quy_Latn", L"Ayakucho kechuasi"},
        {"ayr_Latn", L"Aymara"},
        {"ban_Latn", L"Bali"},
        {"bam_Latn", L"Bambara"},
        {"bjn_Arab", L"Banjar (arab)"},
        {"bjn_Latn", L"Banjar (lotin)"},
        {"eus_Latn", L"Bask"},
        {"bel_Cyrl", L"Belarus"},
        {"bem_Latn", L"Bemba"},
        {"ben_Beng", L"Bengal"},
        {"mya_Mymr", L"Birman"},
        {"bul_Cyrl", L"Bolgar"},
        {"bak_Cyrl", L"Boshqird"},
        {"bos_Latn", L"Bosniy"},
        {"bug_Latn", L"Bugi"},
        {"bho_Deva", L"Bxojpuri"},
        {"nya_Latn", L"Cheva"},
        {"ces_Latn", L"Chex"},
        {"cjk_Latn", L"Chokve"},
        {"hne_Deva", L"Chxattisgarxi"},
        {"dan_Latn", L"Dan"},
        {"prs_Arab", L"Dari"},
        {"dik_Latn", L"Dinka"},
        {"dyu_Latn", L"Diula"},
        {"dzo_Tibt", L"Dzongka"},
        {"epo_Latn", L"Esperanto"},
        {"est_Latn", L"Estoncha"},
        {"ewe_Latn", L"Eve"},
        {"fao_Latn", L"Farercha"},
        {"fij_Latn", L"Fiji"},
        {"tgl_Latn", L"Filipincha"},
        {"fin_Latn", L"Fincha"},
        {"fon_Latn", L"Fon"},
        {"pes_Arab", L"Fors"},
        {"fra_Latn", L"Fransuzcha"},
        {"fur_Latn", L"Friul"},
        {"hat_Latn", L"Gaityan"},
        {"glg_Latn", L"Galisiy"},
        {"lug_Latn", L"Ganda"},
        {"ell_Grek", L"Grek"},
        {"kat_Geor", L"Gruzincha"},
        {"grn_Latn", L"Guarani"},
        {"guj_Gujr", L"Gujarot"},
        {"hin_Deva", L"Hind"},
        {"ydd_Hebr", L"Idish"},
        {"ibo_Latn", L"Igbo"},
        {"ilo_Latn", L"Iloko"},
        {"ind_Latn", L"Indonez"},
        {"eng_Latn", L"Inglizcha"},
        {"gle_Latn", L"Irland"},
        {"acm_Arab", L"Iroq arabchasi"},
        {"isl_Latn", L"Island"},
        {"spa_Latn", L"Ispancha"},
        {"ita_Latn", L"Italyan"},
        {"heb_Hebr", L"Ivrit"},
        {"ajp_Arab", L"Janubiy Levant arabchasi"},
        {"azb_Arab", L"Janubiy ozarbayjon"},
        {"pbt_Arab", L"Janubiy pushtu"},
        {"sot_Latn", L"Janubiy soto"},
        {"kab_Latn", L"Kabil"},
        {"kbp_Latn", L"Kabiye"},
        {"kea_Latn", L"Kabuverdianu"},
        {"kac_Latn", L"Kachin"},
        {"kam_Latn", L"Kamba"},
        {"kan_Knda", L"Kannada"},
        {"yue_Hant", L"Kanton"},
        {"knc_Arab", L"Kanuri (arab)"},
        {"knc_Latn", L"Kanuri (lotin)"},
        {"kas_Arab", L"Kashmircha (arab)"},
        {"kas_Deva", L"Kashmircha (devanagari)"},
        {"cat_Latn", L"Katalan"},
        {"kik_Latn", L"Kikuyu"},
        {"kmb_Latn", L"Kimbundu"},
        {"kin_Latn", L"Kinyaruanda"},
        {"kon_Latn", L"Kongo"},
        {"kor_Hang", L"Koreyscha"},
        {"kmr_Latn", L"Kurdcha"},
        {"xho_Latn", L"Kxosa"},
        {"lao_Laoo", L"Laos"},
        {"ltg_Latn", L"Latgal"},
        {"lvs_Latn", L"Latishcha"},
        {"lij_Latn", L"Liguryan"},
        {"lim_Latn", L"Limburg"},
        {"lin_Latn", L"Lingala"},
        {"lit_Latn", L"Litva"},
        {"lmo_Latn", L"Lombard"},
        {"lua_Latn", L"Luba-lulua"},
        {"luo_Latn", L"Luo"},
        {"lus_Latn", L"Lushay"},
        {"ltz_Latn", L"Lyuksemburgcha"},
        {"mag_Deva", L"Magahi"},
        {"mkd_Cyrl", L"Makedon"},
        {"plt_Latn", L"Malagasiy"},
        {"zsm_Latn", L"Malay"},
        {"mal_Mlym", L"Malayalam"},
        {"mlt_Latn", L"Maltiy"},
        {"mni_Beng", L"Manipur"},
        {"mri_Latn", L"Maori"},
        {"mar_Deva", L"Maratxi"},
        {"tzm_Tfng", L"Markaziy atlas tamazigxt"},
        {"ary_Arab", L"Marokash arabchasi"},
        {"mai_Deva", L"Maythili"},
        {"min_Latn", L"Minangkabau"},
        {"arz_Arab", L"Misr arabchasi"},
        {"khk_Cyrl", L"Mongol"},
        {"mos_Latn", L"Mossi"},
        {"ars_Arab", L"Najd arab"},
        {"deu_Latn", L"Nemischa"},
        {"npi_Deva", L"Nepal"},
        {"nld_Latn", L"Niderland"},
        {"fuv_Latn", L"Nigeriya fulfuldesi"},
        {"nob_Latn", L"Norveg-bokmal"},
        {"nno_Latn", L"Norveg-nyunorsk"},
        {"nus_Latn", L"Nuer"},
        {"uzn_Latn", L"Oʻzbek"},
        {"oci_Latn", L"Oksitan"},
        {"ory_Orya", L"Oriya"},
        {"gaz_Latn", L"Oromo"},
        {"azj_Latn", L"Ozarbayjon"},
        {"pag_Latn", L"Pangasinan"},
        {"pan_Guru", L"Panjobcha"},
        {"pap_Latn", L"Papiyamento"},
        {"pol_Latn", L"Polyakcha"},
        {"por_Latn", L"Portugalcha"},
        {"kir_Cyrl", L"Qirgʻizcha"},
        {"kaz_Cyrl", L"Qozoqcha"},
        {"crh_Latn", L"Qrim tatarchasi"},
        {"ron_Latn", L"Rumincha"},
        {"run_Latn", L"Rundi"},
        {"rus_Cyrl", L"Ruscha"},
        {"smo_Latn", L"Samoa"},
        {"sag_Latn", L"Sango"},
        {"san_Deva", L"Sanskrit"},
        {"sat_Beng", L"Santali"},
        {"srd_Latn", L"Sardin"},
        {"ceb_Latn", L"Sebuan"},
        {"srp_Cyrl", L"Serbcha"},
        {"shn_Mymr", L"Shan"},
        {"apc_Arab", L"Shimoliy Levant arabchasi"},
        {"nso_Latn", L"Shimoliy soto"},
        {"sna_Latn", L"Shona"},
        {"gla_Latn", L"Shotland-gel"},
        {"swe_Latn", L"Shved"},
        {"szl_Latn", L"Silez"},
        {"snd_Arab", L"Sindhi"},
        {"sin_Sinh", L"Singal"},
        {"scn_Latn", L"Sitsiliya"},
        {"slk_Latn", L"Slovakcha"},
        {"slv_Latn", L"Slovencha"},
        {"som_Latn", L"Somalicha"},
        {"ckb_Arab", L"Sorani-kurd"},
        {"arb_Arab", L"Standart arab"},
        {"swh_Latn", L"Suaxili"},
        {"sun_Latn", L"Sundan"},
        {"ssw_Latn", L"Svati"},
        {"taq_Latn", L"Tamashek (lotin)"},
        {"taq_Tfng", L"Tamashek (tifinag)"},
        {"tam_Taml", L"Tamil"},
        {"tat_Cyrl", L"Tatar"},
        {"tha_Thai", L"Tay"},
        {"tel_Telu", L"Telugu"},
        {"bod_Tibt", L"Tibet"},
        {"tir_Ethi", L"Tigrinya"},
        {"tgk_Cyrl", L"Tojik"},
        {"tpi_Latn", L"Tok-piksin"},
        {"tso_Latn", L"Tsonga"},
        {"tsn_Latn", L"Tsvana"},
        {"tum_Latn", L"Tumbuka"},
        {"aeb_Arab", L"Tunis arabchasi"},
        {"tur_Latn", L"Turk"},
        {"tuk_Latn", L"Turkman"},
        {"ukr_Cyrl", L"Ukrain"},
        {"umb_Latn", L"Umbundu"},
        {"urd_Arab", L"Urdu"},
        {"uig_Arab", L"Uygʻur"},
        {"cym_Latn", L"Valliy"},
        {"war_Latn", L"Varay"},
        {"vec_Latn", L"Venet"},
        {"hun_Latn", L"Venger"},
        {"wol_Latn", L"Volof"},
        {"vie_Latn", L"Vyetnam"},
        {"hau_Latn", L"Xausa"},
        {"zho_Hant", L"Xitoy (anʼanaviy)"},
        {"zho_Hans", L"Xitoy (soddalashtirilgan)"},
        {"khm_Khmr", L"Xmer"},
        {"hrv_Latn", L"Xorvat"},
        {"acq_Arab", L"Yaman arabchasi"},
        {"jpn_Jpan", L"Yapon"},
        {"jav_Latn", L"Yavan"},
        {"yor_Latn", L"Yoruba"},
        {"zul_Latn", L"Zulu"},
    };
    return royxat;
}

const Til* top(const std::string& nllb) {
    for (const auto& t : hammasi()) {
        if (t.nllb == nllb) return &t;
    }
    return nullptr;
}

}  // namespace Tillar
}  // namespace rubai
